model_list:
  - model_name: bedrock-claude-3-sonnet
    litellm_params:
      model: "bedrock/anthropic.claude-3-sonnet-20240229-v1:0"
  - model_name: bedrock-llama3-8b-instruct-v1
    litellm_params:
      model: "bedrock/meta.llama3-8b-instruct-v1:0"
  - model_name: bedrock-mixtral-8x7b-instruct-v0
    litellm_params:
      model: "bedrock/mistral.mixtral-8x7b-instruct-v0:1"